# Generated by Django 4.2.6 on 2023-10-25 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.CharField(blank=True, default=datetime.datetime(2023, 10, 25, 17, 28, 7, 809062), null=True, verbose_name='последний вход'),
        ),
    ]
