# Generated by Django 4.2.6 on 2023-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='цена'),
        ),
    ]
