# Generated by Django 4.2.6 on 2023-10-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_course_cost_lesson_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка'),
        ),
    ]
