# Generated by Django 4.2.6 on 2023-10-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ссылка'),
        ),
    ]
